image: alpine:latest
before_script:
  - apk add --no-cache openjdk8 plantuml bash gawk pandoc imagemagick minify libxml2 libxml2-utils
pages:
  script:
    - ./daemon.sh -o
  artifacts:
    paths:
      - public
    expire_in: 2w
  rules:
    # This ensures that only pushes to the default branch will trigger a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
